version: '3.3'
services:
  db:
    image: postgres:13
    container_name: postgres_13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./:/opt/scripts

volumes:
  db:
